server:
  port: 8080

spring:
  application:
    name: test

  h2:
    console:
      enabled: true
      path: /h2-console

    datasource:
      jdbc-url: jdbc:h2:mem:mybatis-test
      hikari:
        maximum-pool-size: 4
      username: test
      password:

  mybatis:
    type-aliases-package: com.example.test.api.entity
    mapper-locations: mybatis-mapper/*.xml


jwt:
  secretKey: SN5OUPJANIZLB/hZ1q7CsJbHvvuZ5xahm6DZMxTZyDI=

  access:
    expiration: 1800000 # 1??(60?) (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h)) ???
    header: Authorization

  refresh:
    expiration: 1209600000 #  (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h) * 24L(h -> ??) * 14(2?)) ???

cookie:
  access:
    expiration: 1800 # ?

  refresh:
    expiration: 1209600 # ?



